PATHS:
  STARTER_DIR: data/raw/starter
  STARTER_INSTANCES: data/instances/starter_instances.txt
  SOLU: data/raw/miplib2017-v35.solu.txt
  PARAMS_SETS: data/params/param_sets.json
  BENCHMARK_FOLDER: /data/raw/benchmark/
  BENCHMARK_CSV: data/raw/The_Benchmark_Set.csv
  OUTPUT_CSV: data/processed/modeldataset.csv
  MODEL_INSTANCES: data/instances/model_instances.txt

SETTINGS:
  TIME_LIMITS: 60
  GAP_THRESHOLD: 0.01

FEATURE_COLS:
  - VariablesVari.
  - BinariesBina.
  - IntegersInte.
  - ContinuousCont.
  - ConstraintsCons.
  - Nonz.Nonz.